version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app
      # - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/centraldocs
      JWT_SECRET: 12345678
      PORT: 3000
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: centraldocs
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: