openapi: 3.0.0
info:
  title: Central Docs Backend API
  version: 1.0.0
  description: API para upload, consulta e histórico de datasets.

servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /auth/register:
    post:
      summary: Registrar novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                senha:
                  type: string
      responses:
        '201':
          description: Usuário registrado
        '400':
          description: Dados inválidos

  /auth/login:
    post:
      summary: Login do usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                senha:
                  type: string
      responses:
        '200':
          description: Login bem-sucedido
        '401':
          description: Credenciais inválidas

  /auth/me:
    get:
      summary: Dados do usuário autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dados do usuário

  /datasets/upload:
    post:
      summary: Upload de dataset (.csv ou .pdf)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Dataset enviado com sucesso

  /datasets:
    get:
      summary: Listar datasets do usuário autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de datasets

  /datasets/{id}/records:
    get:
      summary: Listar registros de um dataset
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista de registros

  /datasets/{id}/records/search:
    get:
      summary: Buscar registros por campo/valor
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
        - in: query
          name: campo
          required: true
          schema:
            type: string
        - in: query
          name: valor
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de registros filtrados

  /queries:
    post:
      summary: Registrar query simulada
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pergunta:
                  type: string
                resposta:
                  type: string
      responses:
        '201':
          description: Query registrada

    get:
      summary: Listar queries do usuário
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de queries